//! Set of instructions interfaces.
pub mod arithmetic;
pub mod assertions;
pub mod assignments;
pub mod binary;
pub mod bitwise;
pub mod canonicity;
pub mod comparison;
pub mod control_flow;
pub mod conversions;
pub mod decomposition;
pub mod ecc;
pub mod equality;
pub mod field;
pub mod hash;
pub mod hash_to_curve;
pub mod map;
pub mod native;
pub mod public_input;
pub mod range_check;
pub mod scalar_field;
pub mod sponge;
pub mod zero;

pub use arithmetic::ArithInstructions;
pub use assertions::AssertionInstructions;
pub use assignments::AssignmentInstructions;
pub use binary::BinaryInstructions;
pub use bitwise::BitwiseInstructions;
pub use canonicity::CanonicityInstructions;
pub use comparison::ComparisonInstructions;
pub use control_flow::ControlFlowInstructions;
pub use conversions::{ConversionInstructions, UnsafeConversionInstructions};
pub use decomposition::DecompositionInstructions;
pub use ecc::EccInstructions;
pub use equality::EqualityInstructions;
pub use field::FieldInstructions;
pub use hash::HashInstructions;
pub use hash_to_curve::{HashToCurveCPU, HashToCurveInstructions};
pub use native::NativeInstructions;
pub use public_input::PublicInputInstructions;
pub use range_check::RangeCheckInstructions;
pub use scalar_field::ScalarFieldInstructions;
pub use sponge::{SpongeCPU, SpongeInstructions};
pub use zero::ZeroInstructions;
