on:
  pull_request:
    paths:
      - 'curves/**'

jobs:
  # Enforces the update of a changelog file on every pull request
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: dangoslen/changelog-enforcer@204e7d3ef26579f4cd0fd759c57032656fdf23c7
        with:
          changeLogPath: curves/CHANGELOG.md