name: Checkmarx One Scan

# ↓ lock down top‐level permissions to only what we use
permissions:
  contents: read             # we only need to checkout code
  actions: read              # to query workflows/runs
  pull-requests: write       # to comment on or label PRs

on:
  pull_request_target:  # Changed from pull_request to pull_request_target
    types: [opened, synchronize, reopened]
    branches: [ '**' ]
  push:
    branches: [ 'main' ]
  workflow_dispatch: {}   # so you can still run it manually
  schedule:
    - cron: "0 0 * * *"   # run daily at midnight UTC
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true
jobs:
  build:
    permissions:
      contents: read
      pull-requests: write
      security-events: write

    runs-on: ubuntu-latest

    steps:
      # CRITICAL: DO NOT CHECKOUT THE PR CODE
      # This is what makes it safe with pull_request_target

      # TODO: Remove this checkout step once upload-sarif-github-action repo is made public
      # Currently required because GitHub Actions can't directly reference private repos
      - name: Checkout Upload action repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          repository: midnightntwrk/upload-sarif-github-action
          ref: 2a471c191b66c5fbd4c2ad79b4de885a919be3bd
          path: upload-sarif-github-action
          token: ${{ secrets.MIDNIGHTCI_REPO }}

      # Once public, can simplify to: uses: midnightntwrk/upload-sarif-github-action/checkmarx-scan@2a471c191b66c5fbd4c2ad79b4de885a919be3bd
      - name: Checkmarx Full Scan
        uses: ./upload-sarif-github-action/checkmarx-scan-public
        with:
          cx-client-id: ${{ secrets.CX_CLIENT_ID }}
          cx-client-secret: ${{ secrets.CX_CLIENT_SECRET_EU }}
          cx-tenant: ${{ secrets.CX_TENANT }}
          scs-repo-token: ${{ secrets.MIDNIGHTCI_REPO }}
          upload-to-github: 'true'
